---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, alarms, cloudwatch, giveback, govcloud, detaching, encryption, snapmanager, features, ha limitations, nfsv4, nfsv3, data tiering, disks, aggregates 
summary: Les limitations connues identifient les plateformes, les périphériques ou les fonctions qui ne sont pas pris en charge par cette version du produit, ou qui ne fonctionnent pas correctement avec elle. Examinez attentivement ces limites. 
---
= Limites connues
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les limitations connues identifient les plateformes, les périphériques ou les fonctions qui ne sont pas pris en charge par cette version du produit, ou qui ne fonctionnent pas correctement avec elle. Examinez attentivement ces limites.



== Limitations générales

Les restrictions suivantes s'appliquent à Cloud Volumes ONTAP dans AWS et dans Azure.



=== Nombre maximal d'opérations de réplication simultanées

Le nombre maximal de transferts SnapMirror ou SnapVault simultanés pour Cloud Volumes ONTAP est de 100 par nœud, indépendamment du type d'instance ou du type d'ordinateur.



=== Les mises à jour logicielles doivent être effectuées par Cloud Manager

La mise à niveau d'Cloud Volumes ONTAP doit être effectuée depuis Cloud Manager. Vous ne devez pas mettre à niveau Cloud Volumes ONTAP à l'aide de System Manager ou de l'interface de ligne de commandes. Cela peut affecter la stabilité du système.



=== Le déploiement Cloud Volumes ONTAP ne doit pas être modifié depuis la console de votre fournisseur cloud

Toute modification apportée à une configuration Cloud Volumes ONTAP depuis la console de votre fournisseur cloud entraîne la prise en charge d'une configuration non prise en charge. Toute modification des ressources Cloud Volumes ONTAP créés et gérées par Cloud Manager peut avoir un impact sur la stabilité du système et la capacité de Cloud Manager à gérer le système.



=== Les disques et les agrégats doivent être gérés depuis Cloud Manager

Tous les disques et agrégats doivent être créés et supprimés directement de Cloud Manager. Vous ne devez pas effectuer ces actions à partir d'un autre outil de gestion. Cela peut avoir un impact sur la stabilité du système, entraver la possibilité d'ajouter des disques à l'avenir et générer potentiellement des frais de fournisseur de cloud redondant.



=== Limitation des licences SnapManager

Les licences SnapManager par serveur sont prises en charge par Cloud Volumes ONTAP. Les licences par système de stockage (suite SnapManager) ne sont pas prises en charge.



=== Fonctions ONTAP non prises en charge

Les fonctionnalités suivantes ne sont pas prises en charge par Cloud Volumes ONTAP :

* Déduplication à la volée au niveau des agrégats
* La déduplication en arrière-plan au niveau de l'agrégat
* Centre de maintenance du disque
* Nettoyage de disque
* Fibre Channel (FC)
* Pools Flash
* FlexCache
* Infinite volumes
* Groupes d'interface
* Le basculement LIF monomode d'un cluster
* MetroCluster
* Colocation (seule une machine virtuelle de service des données est prise en charge)
* RAID4, RAID-DP, RAID-TEC (RAID0 PRIS EN CHARGE)
* Le processeur de service
* Modes SnapLock Compliance et Enterprise (seul le mode WORM cloud est pris en charge)
* SnapMirror synchrone
* VLAN




== Restrictions connues dans AWS

Les restrictions connues suivantes affectent Cloud Volumes ONTAP dans AWS.



=== Limites de Flash cache

Les types d'instances C5D et R5D incluent le stockage NVMe local, que Cloud Volumes ONTAP utilise comme _Flash cache_. Notez les limites suivantes :

* La compression doit être désactivée sur tous les volumes pour tirer parti des améliorations des performances de Flash cache.
+
Vous pouvez choisir aucune efficacité du stockage lors de la création d'un volume depuis Cloud Manager, ou encore créer un volume, puis http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/GUID-8508A4CB-DB43-4D0D-97EB-859F58B29054.html["Désactiver la compression des données à l'aide de l'interface de ligne de commande"^].

* La réactivation du cache après un redémarrage n'est pas prise en charge avec Cloud Volumes ONTAP.




=== Fausses alarmes signalées par Amazon CloudWatch

Cloud Volumes ONTAP ne libère pas les processeurs lorsqu'ils sont inactifs, Amazon CloudWatch peut signaler un avertissement important concernant le CPU pour l'instance EC2 car il détecte une utilisation de 100 %. Vous pouvez ignorer cette alarme. La commande ONTAP statistics affiche la véritable utilisation des CPU.



=== Les paires haute disponibilité Cloud Volumes ONTAP ne prennent pas en charge le rétablissement immédiat du stockage

Après le redémarrage d'un nœud, le partenaire doit synchroniser les données pour qu'il puisse renvoyer le système de stockage. Le temps nécessaire pour resynchroniser les données dépend de la quantité de données écrites par les clients alors que le nœud était en panne et de la vitesse d'écriture des données pendant le rétablissement.



=== Limitations de l'environnement AWS C2S

Consultez les limites de la documentation Cloud Manager : https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-getting-started-aws-c2s.html["Lancez-vous dans l'environnement AWS C2S"^]



=== Limitations dans les régions AWS GovCloud (USA)

* Cloud Manager doit être déployé dans une région AWS GovCloud (USA) si vous souhaitez lancer les instances Cloud Volumes ONTAP dans toute région AWS GovCloud (USA).
* Lorsqu'il est déployé sur une région AWS GovCloud (USA), Cloud Manager ne peut pas détecter les clusters ONTAP dans une configuration NetApp Private Storage pour Microsoft Azure ou dans une configuration NetApp Private Storage pour SoftLayer.




=== La déconnexion et la reconnexion des volumes EBS n'est pas prise en charge

La déconnexion d'un volume EBS d'une instance Cloud Volumes ONTAP, puis sa connexion à une autre instance Cloud Volumes ONTAP n'est pas prise en charge. Vous devez utiliser Cloud Manager pour répliquer les données entre instances.



== Restrictions connues de Microsoft Azure

Cloud Volumes ONTAP s'est limité dans Azure par les restrictions connues suivantes.



=== Les nouveaux déploiements ne sont pas pris en charge

Les nouveaux déploiements de Cloud Volumes ONTAP 9.5 ne sont plus pris en charge dans Azure. Vous devez déployer Cloud Volumes ONTAP 9.7.



=== Limitations de LA HAUTE DISPONIBILITÉ

Les limites suivantes affectent les paires HA Cloud Volumes ONTAP dans Microsoft Azure :

* Le Tiering des données n'est pas pris en charge.
* NFSv4 n'est pas pris en charge. NFSv3 est pris en charge.
* Les paires HA ne sont pas prises en charge dans certaines régions.
+
https://cloud.netapp.com/cloud-volumes-global-regions["Consultez la liste des régions Azure prises en charge"^].


